namespace 毕业设计
{
    partial class FormShowTempHumiTable
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.plotSurface2D_tempHumi = new NPlot.Windows.PlotSurface2D();
            this.SuspendLayout();
            // 
            // plotSurface2D_tempHumi
            // 
            this.plotSurface2D_tempHumi.AutoScaleAutoGeneratedAxes = false;
            this.plotSurface2D_tempHumi.AutoScaleTitle = false;
            this.plotSurface2D_tempHumi.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.plotSurface2D_tempHumi.DateTimeToolTip = false;
            this.plotSurface2D_tempHumi.Legend = null;
            this.plotSurface2D_tempHumi.LegendZOrder = -1;
            this.plotSurface2D_tempHumi.Location = new System.Drawing.Point(12, 22);
            this.plotSurface2D_tempHumi.Name = "plotSurface2D_tempHumi";
            this.plotSurface2D_tempHumi.RightMenu = null;
            this.plotSurface2D_tempHumi.ShowCoordinates = true;
            this.plotSurface2D_tempHumi.Size = new System.Drawing.Size(534, 379);
            this.plotSurface2D_tempHumi.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.plotSurface2D_tempHumi.TabIndex = 0;
            this.plotSurface2D_tempHumi.Text = "plotSurface2D1";
            this.plotSurface2D_tempHumi.Title = "";
            this.plotSurface2D_tempHumi.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.plotSurface2D_tempHumi.XAxis1 = null;
            this.plotSurface2D_tempHumi.XAxis2 = null;
            this.plotSurface2D_tempHumi.YAxis1 = null;
            this.plotSurface2D_tempHumi.YAxis2 = null;
            // 
            // FormShowTempHumiTable
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(607, 413);
            this.Controls.Add(this.plotSurface2D_tempHumi);
            this.Name = "FormShowTempHumiTable";
            this.Text = "FormShowTempHumiTable";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.FormShowTempHumiTable_FormClosed);
            this.Load += new System.EventHandler(this.FormShowTempHumiTable_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private NPlot.Windows.PlotSurface2D plotSurface2D_tempHumi;

    }
}